/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-04-02 03:26:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1712027043861L));
    _jspx_dependants.put("jar:file:/C:/testSemi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gameProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>gameProject</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/0ddb604158.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <!-- header include -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"main-footer-wrap\">\r\n");
      out.write("            <main>\r\n");
      out.write("                <!-- slide include -->\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/slide.jsp", out, false);
      out.write("\r\n");
      out.write("                <section class=\"main-wrap\">\r\n");
      out.write("                    <div class=\"main-title\">\r\n");
      out.write("                        <h2>사람들과 게임 점수를 경쟁해보세요!</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"main-content\">\r\n");
      out.write("                        <div class=\"m-con-top\">\r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/tetris\"><img src=\"https://png.pngtree.com/thumb_back/fw800/background/20230527/pngtree-tetris-wallpaper-hd-1080p-image_2693812.jpg\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">추억의 게임 테트리스는 어때요?</p>\r\n");
      out.write("                                <p class=\"con-box-text\">1985년 세상에 등장한 명작</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/snake\"><img src=\"https://play-lh.googleusercontent.com/L9opLtUUqK0yOTq7uXTou1B4jyqf5Z_kTIG8CShM6tpsXLMTEjg5GVDzcnAO7GxOk9w7\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">벽에 닿지말고 최대한 길게 몸을 늘려보세요!</p>\r\n");
      out.write("                                <p class=\"con-box-text\">매우 간단한 스네이크 게임</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/rsp\"><img src=\"https://img1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/6Opp/image/nJtTUmhg2apMuSs8mJPK18enXEc.jpg\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">컴퓨터와 함께하는 두근두근♥ 가위바위보 게임</p>\r\n");
      out.write("                                <p class=\"con-box-text\">쉽게 이길 수 있을까요?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"m-con-bottom\">\r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/upDown\"><img src=\"https://upup.fm/images/logo.png\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">위 ↑아래↓ 위위↑↑ 아래↓</p>\r\n");
      out.write("                                <p class=\"con-box-text\">UPDOWN GAME!</p>\r\n");
      out.write("                            </div>                        \r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/baseball\"><img src=\"https://static.indischool.com/images/users/65b5fe18ba01c21a7fd634d337a5d361/739321bf-37b9-49f8-8a2e-32d3aa6010c3.png\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">과연 몇번의 기회 안에 맞출 수 있을까요?</p>\r\n");
      out.write("                                <p class=\"con-box-text\">제가 1994년 LA에 있었을 때...</p>\r\n");
      out.write("                            </div>                        \r\n");
      out.write("                            <div class=\"con-box\">\r\n");
      out.write("                                <div class=\"img-wrap\">\r\n");
      out.write("                                    <a href=\"game/snail\"><img src=\"https://image.cine21.com/resize/cine21/article/2013/0722/16_59_46__51ece6723e220[S800,800].jpg\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"con-box-title\">어디서 많이 본 거 같지만 기분 탓인 달팽이 게임</p>\r\n");
      out.write("                                <p class=\"con-box-text\">달팽이 게임</p>\r\n");
      out.write("                            </div>                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </main>\r\n");
      out.write("            <!-- 푸터 include  -->\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
